### ISSUE TITLE
fix: Cannot find module @unhead/schema imported from

### ISSUE THREAD

**Issue by aligzl** [harlan-zw/nuxt-seo#363]
### 🐛 The bug

Having fallowing error when updated to 2.0.2

 ERROR  Could not compile template module/nuxt-seo-utils.d.ts.                                                                      10:20:05 AM

[10:20:05 AM]  ERROR  Cannot find module @unhead/schema imported from file:///Users/aliguzel/Desktop/Webs/masaiballoons.com, file file:///node_modules/web/ _index.js, file:///node_modules

 at _resolve (node_modules/.pnpm/mlly@1.7.3/node_modules/mlly/dist/index.mjs:2102:19)
  at resolveSync (node_modules/.pnpm/mlly@1.7.3/node_modules/mlly/dist/index.mjs:2111:10)
  at resolvePathSync (node_modules/.pnpm/mlly@1.7.3/node_modules/mlly/dist/index.mjs:2121:24)
  at resolvePath (node_modules/.pnpm/mlly@1.7.3/node_modules/mlly/dist/index.mjs:2125:28)
  at node_modules/.pnpm/nuxt-seo-utils@6.0.1_magicast@0.3.5_rollup@4.27.4_vite@5.4.11_@types+node@22.9.3_terser@5.36._agf7nne5e4i7t6imzuws3kb3my/node_modules/nuxt-seo-utils/dist/module.mjs:502:111
  at Object.getContents (node_modules/.pnpm/nuxt-seo-utils@6.0.1_magicast@0.3.5_rollup@4.27.4_vite@5.4.11_@types+node@22.9.3_terser@5.36._agf7nne5e4i7t6imzuws3kb3my/node_modules/nuxt-seo-utils/dist/module.mjs:41:23)
  at futureCompileTemplate (node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.9.3_drizzle-orm@0.36.4_@cloudflare+worker_bygtw7gcmbrh2pdpowdgx5zo3i/node_modules/nuxt/dist/index.mjs:5507:21)
  at processTemplate (node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.9.3_drizzle-orm@0.36.4_@cloudflare+worker_bygtw7gcmbrh2pdpowdgx5zo3i/node_modules/nuxt/dist/index.mjs:5460:28)
  at Array.map (<anonymous>)
  at generateApp (node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.9.3_drizzle-orm@0.36.4_@cloudflare+worker_bygtw7gcmbrh2pdpowdgx5zo3i/node_modules/nuxt/dist/index.mjs:5487:50)

### 🛠️ To reproduce

No reproduction needed

### 🌈 Expected behavior

Works as expected without errors.

### ℹ️ Additional context

- Operating System: `Darwin`
- Node Version:     `v21.7.3`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `pnpm@9.9.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/eslint@0.7.1`, `@nuxthub/core@0.8.7`, `@nuxt/ui`, `@nuxtjs/seo@2.0.2`, `@nuxtjs/i18n@9.1.0`, `@nuxtjs/cloudinary@4.0.0`, `nuxt-auth-utils@0.5.5`, `@nuxt/scripts@0.9.5`
- Build Modules:    `-`
